### ISSUE TITLE
파일 정보 받아오기

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#1]
stat1, stat2에 각각 text1, text2의 파일정보를 불러오도록 함수 작성하겠음.

**Comment by euwnsep1225** [comment]
어떻게 불러오는지 코드를 올려주시거나 사이트를 올려주시면 감사하겠습니다.

**Comment by minhodang** [comment]
void filestat1(void)
{
	stat("text1", &stat1);
}

와 같이 stat을 활용하여 text1파일의 정보를 stat1에 저장함.
