### ISSUE TITLE
파일 수정 날짜(월/일) 비교 코드 작성

### ISSUE THREAD

**Issue by euwnsep1225** [euwnsep1225/Assignment2#1]
void datecmp(void)
{
	printf("date compare\n");
	time1 = localtime(&stat1.st_mtime);
	time2 = localtime(&stat2.st_mtime);
	if ((time1->tm_mon+1) == (time2->tm_mon+1)) {
		if (time1->tm_mday == time2->tm_mday)
			printf("same time\n");
		else if (time1->tm_mday > time2->tm_mday)
			printf("text1 is early\n");
		else
			printf("text2 is early\n");
	}
	else if ((time1->tm_mon+1) > (time2->tm_mon+1))
		printf("text1 is early\n");
	else
		printf("text2 is early\n");
}

월은 1월부터 0을 의미하기 때문에 +1을 해주었고 날짜가 클수록 최신이라 생각하여 코드를 작성했습니다.

**Comment by minhodang** [comment]
time1 = localtime(&stat1.st_mtime);
 time2 = localtime(&stat2.st_mtime);
은 별도 함수에서 정의하기 때문에 실제 코딩시는 빼는걸 고려해야할 듯 합니다.

**Comment by euwnsep1225** [comment]
네 올려주신 코드 적용하고 테스트 해보겠습니다.

**Comment by shine8917** [comment]
확인했습니다.

**Comment by euwnsep1225** [comment]
void datecmp(void)
{

	printf("date compare\n");
	if ((time1->tm_mon + 1) == (time2->tm_mon + 1)) {
		if (time1->tm_mday == time2->tm_mday)
			printf("same time\n");
		else if (time1->tm_mday > time2->tm_mday)
			printf("text1 is early\n");
		else
			printf("text2 is early\n");
	}
	else if ((time1->tm_mon + 1) > (time2->tm_mon + 1))
		printf("text1 is early\n");
	else
		printf("text2 is early\n");

}

수정해서 Pull Request보내겠습니다.

**Comment by minhodang** [comment]
네. 확인했습니다.
