### ISSUE TITLE
파일 시간 받아오기 코드 조사

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#10]
stat 구조체의 st_mtime의 수정된 시간 정보를 읽어

tm 구조체의 변수로 저장해 각각 일, 월, 시, 분의 정보로 나눠서 관리/표시 함

localtime() : tm구조체 형식에 맞게 시간 데이터를 읽어드림

tm_mon : 월(0~11)

tm_mday : 일

tm_hour : 시간

tm_min : 분

출처 : 과제2 Appendix 19p

**Comment by euwnsep1225** [comment]
네 참고하겠습니다.
