### ISSUE TITLE
파일 시간 가져오기 코드 작성

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#11]
*파일 정보가저오기에서 각각 stat1과 stat2에 파일정보를 읽었다는 가정 후에 작성

#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>

struct stat stat1, stat2;
struct tm *time1, *time2;

//파일 1의 시간 정보를 가져오는 함수 작성
void filetime1(void)
{
    time1 = localtime(&stat1.st_mtime);
}

//파일 2의 시간 정보를 가져오는 함수 작성
void filetime2(void)
{
    time2 = localtime(&stat2.st_mtime);
}

**Comment by euwnsep1225** [comment]
제 코드에 적용해 보겠습니다.

**Comment by minhodang** [comment]
참고하겠습니다.
