### ISSUE TITLE
파일 시간 가져오기 코드 테스트

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#12]
printf("text1 modified time : %d : %d \n",time1->tm_hour,time1->tm_min);
printf("text2 modified time : %d : %d \n",time2->tm_hour,time2->tm_min);
을 추가하여 정상적으로 시간이 출력되는지 확인함

결과는 첨부파일 참고
![2](https://user-images.githubusercontent.com/38343803/39194123-81f2a0ce-47cc-11e8-941d-453d5286016f.jpg)

**Comment by euwnsep1225** [comment]
리눅스 상에서 ls -al로 실제 파일의 수정된 시간도 같이 올려주시면 감사하겠습니다.

**Comment by minhodang** [comment]
테스트 파일을 삭제해 버렸습니다....

테스트 단계에서 확인시 ls로 시간은 확인했습니다.

**Comment by euwnsep1225** [comment]
네 알겠습니다.
코드 merge하고서 테스트 결과를 올리겠습니다.
