### ISSUE TITLE
파일 사이즈 비교 코드 테스트

### ISSUE THREAD

**Issue by shine8917** [euwnsep1225/Assignment2#15]
임의의 text1, text2 파일을 만들고 코드를 실행해 보았습니다.
![image](https://user-images.githubusercontent.com/31432004/39221980-f9e384b0-4874-11e8-97a4-96ffe098ab32.png)

**Comment by euwnsep1225** [comment]
리눅스에서 ls -al로 두 파일의 사이즈도 보여주실 수 있나요?

**Comment by minhodang** [comment]
참고하겠습니다.
