### ISSUE TITLE
파일 블락 수 비교 코드 테스트

### ISSUE THREAD

**Issue by shine8917** [euwnsep1225/Assignment2#18]
파일 text1, text2를 만들고 실행했습니다.
![image](https://user-images.githubusercontent.com/31432004/39222189-4ff42264-4876-11e8-8c42-48f8cc46de35.png)

**Comment by euwnsep1225** [comment]
사이즈와 마찬가지로 리눅스에서 ls -al로 두 파일의 사이즈도 같이 보여주면 감사하겠습니다.

**Comment by minhodang** [comment]
참고하겠습니다.
