### ISSUE TITLE
파일 수정 날짜(월/일) 비교 코드 테스트

### ISSUE THREAD

**Issue by euwnsep1225** [euwnsep1225/Assignment2#2]
코드 실행시켰을 때 화면입니다.
![1](https://user-images.githubusercontent.com/38311926/39126066-1b023e0a-473c-11e8-8323-81e30d10696f.JPG)

파일의 날짜입니다.
![2](https://user-images.githubusercontent.com/38311926/39126095-3a1e9554-473c-11e8-865b-ff9c2c5a91fd.JPG)

**Comment by minhodang** [comment]
good job!

**Comment by shine8917** [comment]
확인했습니다.
