### ISSUE TITLE
파일 정보 가져오기

### ISSUE THREAD

**Issue by euwnsep1225** [euwnsep1225/Assignment2#23]
![6](https://user-images.githubusercontent.com/38311926/39226254-372132f2-488c-11e8-94a3-ab49129d18ae.JPG)

merge하고서 확인해보니 에러가 발생했네요;;;
다시 수정해주시고 PR 보내주세요.

제대로 확인 못하고 merge한 점 죄송합니다.;;

**Comment by minhodang** [comment]
수정하고 PR 올리겠습니다.
