### ISSUE TITLE
파일 수정 시간(시/분) 비교 코드

### ISSUE THREAD

**Issue by euwnsep1225** [euwnsep1225/Assignment2#3]
void timecmp(void)
{
	printf("time compare\n");
	time1 = localtime(&stat1.st_mtime);
	time2 = localtime(&stat2.st_mtime);
	if (time1->tm_hour == time2->tm_hour) {
		if (time1->tm_min == time2->tm_min)
			printf("same time\n");
		else if (time1->tm_min > time2->tm_min)
			printf("text1 is early\n");
		else
			printf("text2 is early\n");
	}
	else if (time1->tm_hour > time2->tm_hour)
		printf("text1 is early\n");
	else
		printf("text2 is early\n");
}

시간이 큰 경우를 최신 파일이라 생각하고 코드를 작성했습니다.

**Comment by minhodang** [comment]
good job!

**Comment by shine8917** [comment]
excellent!!

**Comment by euwnsep1225** [comment]
void timecmp(void)
{

	printf("time compare\n");
	if (time1->tm_hour == time2->tm_hour) {
		if (time1->tm_min == time2->tm_min)
			printf("same time\n");
		else if (time1->tm_min > time2->tm_min)
			printf("text1 is early\n");
		else
			printf("text2 is early\n");
	}
	else if (time1->tm_hour > time2->tm_hour)
		printf("text1 is early\n");
	else
		printf("text2 is early\n");

}

시간도 다시 수정해서 PR 보내겠습니다.

**Comment by shine8917** [comment]
넵. 확인했습니다~
