### ISSUE TITLE
파일 수정 시간(시/분) 비교 코드 테스트

### ISSUE THREAD

**Issue by euwnsep1225** [euwnsep1225/Assignment2#4]
코드를 디버깅하면서 실행결과를 확인했습니다.

![3](https://user-images.githubusercontent.com/38311926/39126277-e00b0d8a-473c-11e8-86c2-451833facc36.JPG)

파일의 시간을 확인했습니다.

![2](https://user-images.githubusercontent.com/38311926/39126307-f7b603cc-473c-11e8-8d2b-efbba9f6d176.JPG)

**Comment by minhodang** [comment]
good job!

**Comment by shine8917** [comment]
확인했습니다.
