### ISSUE TITLE
파일 정보 받아오기 코드 조사

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#5]
struct stat : 파일의 정보를 정의하는 구조체

구성요소(과제의 필요한 요소 한정)

st_size : 파일의 크기를 저장

st_blocks : 파일의 블록 사이즈를 저장

st_mtime : 파일의 최종 변경시간을 저장

**Comment by minhodang** [comment]
출처 : 과제2 Appendix 18p

**Comment by shine8917** [comment]
감사합니다
