### ISSUE TITLE
파일 정보 받아오기 코드 작성

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#6]
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>

struct stat stat1, stat2;
struct tm *time1, *time2;

//파일 1의 정보를 가져오는 함수 작성
void filestat1(void)
{
      stat("text1", &stat1);
}

//파일 2의 정보를 가져오는 함수 작성
void filestat2(void)
{
     stat("text2", &stat2);
}

**Comment by euwnsep1225** [comment]
네 확인했습니다.
제 코드에 적용시켜 볼게요

**Comment by shine8917** [comment]
넵

**Comment by euwnsep1225** [comment]
stat 함수의 반환값이 있던데 파일을 못받을 경우를 생각해서 조건문을 걸어주시는건 어떤가요?

**Comment by minhodang** [comment]
말씀하신대로 예외처리문 포함해서 추가 PR 하겠습니다.

**Comment by euwnsep1225** [comment]
네 확인했습니다.
