### ISSUE TITLE
파일 정보 받아오기 코드 테스팅

### ISSUE THREAD

**Issue by minhodang** [euwnsep1225/Assignment2#7]
printf("text1의 파일사이즈 : %d \n", stat1.st_size);
printf("text2의 파일사이즈 : %d \n", stat2.st_size);
를 추가하여 정상적으로 파일 정보가 stat1과 stat2에 저장됬는지 확인함.

테스트 결과를 첨부파일 참조
![1](https://user-images.githubusercontent.com/38343803/39191771-36f3b540-47c7-11e8-80e2-0620155355cd.jpg)

**Comment by euwnsep1225** [comment]
파일은 따로 만드셔서 하신건가요?

**Comment by minhodang** [comment]
포크 전에 작성한 거라 별도 파일 만들어서 테스트 했습니다.

**Comment by shine8917** [comment]
확인했습니다
