### ISSUE TITLE
파일 수정 시간(시/분) 및 날짜(월/일) 사전 조사

### ISSUE THREAD

**Issue by euwnsep1225** [euwnsep1225/Assignment2#9]
1. struct stat 정보
URL : https://www.joinc.co.kr/w/man/2/stat

1.1. 마지막 수정 시간
time_t        st_mtime;    /* time of last modification */

2. localtime() 함수
URL : https://msdn.microsoft.com/ko-kr/library/bf12f0hc.aspx

2.1. localtime() 함수를 쓰는 이유
stat() 함수를 통해서 마지막 수정 시간을 받아오면 알아보기 쉬운 시간이 아니기 때문에 localtime() 함수를 통해서 tm 구조체에 알아보기 쉬운 정보로 저장합니다.

3. struct tm 정보
URL : http://mwultong.blogspot.com/2006/10/c-timeh-struct-tm-time-structure.html

3.1. 시간(시/분)
int tm_min;   /* Minutes */
int tm_hour;  /* Hour (0--23) */

3.2. 날짜(월/일)
int tm_mday;  /* Day of month (1--31) */
int tm_mon;   /* Month (0--11) */

**Comment by shine8917** [comment]
이렇게 다양한 함수가 있다니! 정말 놀라운걸요!!

**Comment by minhodang** [comment]
참고하겠습니다.
